// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMoomf7TATLY5kU0vcOffk8PdgrwSGI-4',
    appId: '1:847142592507:web:7550ba393202fcb54d755e',
    messagingSenderId: '847142592507',
    projectId: 'authtutorial-b984c',
    authDomain: 'authtutorial-b984c.firebaseapp.com',
    databaseURL: 'https://authtutorial-b984c-default-rtdb.firebaseio.com',
    storageBucket: 'authtutorial-b984c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1l70DI69XkWgUsKFsQ3sCdfG1x83Hw1w',
    appId: '1:847142592507:android:35d466fff0de7eeb4d755e',
    messagingSenderId: '847142592507',
    projectId: 'authtutorial-b984c',
    databaseURL: 'https://authtutorial-b984c-default-rtdb.firebaseio.com',
    storageBucket: 'authtutorial-b984c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHXmrwSPFA6TbEq-iZ9ph1BimNhQ7sR1Q',
    appId: '1:847142592507:ios:beb337e9d39b9b784d755e',
    messagingSenderId: '847142592507',
    projectId: 'authtutorial-b984c',
    databaseURL: 'https://authtutorial-b984c-default-rtdb.firebaseio.com',
    storageBucket: 'authtutorial-b984c.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHXmrwSPFA6TbEq-iZ9ph1BimNhQ7sR1Q',
    appId: '1:847142592507:ios:0c5de8c604b47d284d755e',
    messagingSenderId: '847142592507',
    projectId: 'authtutorial-b984c',
    databaseURL: 'https://authtutorial-b984c-default-rtdb.firebaseio.com',
    storageBucket: 'authtutorial-b984c.appspot.com',
    iosBundleId: 'com.example.flutterApplication3.RunnerTests',
  );
}
